apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-cronjob
spec:
  schedule: "*/2 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ping-container
            image: busybox  
            command: ["sh", "-c", "ping -c 4 8.8.8.8"]
          restartPolicy: OnFailure